version: "3.8"

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db

  app:
    image: bizforward-testapp
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      TS_NODE_PROJECT: 1
    ports:
      - 8888:8888

  test:
    image: golang:1.18
    volumes:
      - ./main_test.go:/app/main_test.go
    command: go run /app/main_test.go
